local off_screen = { };
off_screen["x"] = 234;
off_screen["y"] = 192;
off_screen["touch"] = true ;

local touch_data = { };
touch_data["touch"] = true ;

touch_data["x"] = 245;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 245;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 241;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 241;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 241;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 237;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 237;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 233;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 233;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 233;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 229;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 229;
touch_data["y"] = 81;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 229;
touch_data["y"] = 62;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 225;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 225;
touch_data["y"] = 61;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 221;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 221;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 217;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 217;
touch_data["y"] = 69;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 213;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 213;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 213;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 209;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 209;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 193;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 193;
touch_data["y"] = 21;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 193;
touch_data["y"] = 14;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 13;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 13;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 176;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 13;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 21;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 21;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 13;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 13;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 5;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 73;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 93;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 105;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 105;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 69;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 69;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 73;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 73;
touch_data["y"] = 113;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 93;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 93;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 97;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 97;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 93;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 93;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 157;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 73;
touch_data["y"] = 157;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 73;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 165;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 165;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 169;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 169;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 173;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 105;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 105;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 109;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 109;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 9;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 21;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 21;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 97;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 45;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 126;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 105;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 105;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 105;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 146;
touch_data["y"] = 61;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 97;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 152;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 97;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 61;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 61;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 81;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 61;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 61;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 61;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 81;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 81;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 81;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 69;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 193;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 193;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 69;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 45;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 77;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 209;
touch_data["y"] = 77;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 209;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 213;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 213;
touch_data["y"] = 44;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 21;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 21;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 158;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 81;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 81;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 113;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 245;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 245;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 241;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 241;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 237;
touch_data["y"] = 105;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 237;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 233;
touch_data["y"] = 105;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 233;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 229;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 229;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 225;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 225;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 221;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 221;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 217;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 217;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 213;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 213;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 209;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 209;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 193;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 193;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 164;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 173;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 165;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 157;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 177;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 177;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 165;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 165;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 114;
touch_data["y"] = 177;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 177;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 109;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 109;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 105;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 105;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 157;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 97;
touch_data["y"] = 165;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 97;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 169;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 173;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 169;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 173;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 181;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
emu.pause();
