local off_screen = { };
off_screen["x"] = 234;
off_screen["y"] = 192;
off_screen["touch"] = true ;

local touch_data = { };
touch_data["touch"] = true ;

touch_data["x"] = 230;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 14;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 16;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 13;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 238;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 238;
touch_data["y"] = 27;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 27;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 234;
touch_data["y"] = 31;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 234;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 237;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 239;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 44;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 55;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 60;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 60;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 239;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 233;
touch_data["y"] = 104;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 233;
touch_data["y"] = 108;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 108;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 237;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 239;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 135;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 238;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 238;
touch_data["y"] = 147;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 147;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 234;
touch_data["y"] = 151;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 234;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 160;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 160;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 164;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 165;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 178;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 178;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 178;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 178;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 11;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 200;
touch_data["y"] = 13;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 200;
touch_data["y"] = 15;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 202;
touch_data["y"] = 15;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 200;
touch_data["y"] = 15;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 200;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 45;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 45;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 203;
touch_data["y"] = 55;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 55;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 116;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 120;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 120;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 116;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 204;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 204;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 202;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 202;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 200;
touch_data["y"] = 136;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 200;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 11;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 15;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 15;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 11;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 27;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 186;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 27;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 32;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 55;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 55;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 72;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 186;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 72;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 79;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 188;
touch_data["y"] = 79;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 76;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 87;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 87;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 91;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 186;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 107;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 115;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 115;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 119;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 120;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 188;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 182;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 182;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 188;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 186;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 131;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 14;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 16;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 131;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 131;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 131;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 148;
touch_data["y"] = 51;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 64;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 122;
touch_data["y"] = 51;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 64;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 148;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 122;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 95;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 93;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 90;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 90;
touch_data["y"] = 14;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 90;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 88;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 13;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 75;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 63;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 75;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 63;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 136;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 136;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
emu.pause();
