local off_screen = { };
off_screen["x"] = 234;
off_screen["y"] = 192;
off_screen["touch"] = true ;

local touch_data = { };
touch_data["touch"] = true ;

touch_data["x"] = 235;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 27;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 218;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 39;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 222;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 222;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 39;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 83;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 218;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 103;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 225;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 222;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 222;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 215;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 219;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 231;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 225;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 227;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 191;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 191;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 195;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 191;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 191;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 195;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 191;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 191;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 159;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 159;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 169;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 150;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 126;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 126;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 127;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 127;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 100;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 163;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 115;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 115;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 126;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 126;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 68;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 135;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 77;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 68;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 79;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 64;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 107;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 14;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 14;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 58;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 58;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 84;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 21;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 68;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 23;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 64;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 51;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 159;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 159;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 58;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 58;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 159;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 159;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 139;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 211;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 199;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 199;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 171;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 171;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 199;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 199;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 171;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 171;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 135;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
emu.pause();
