local off_screen = { };
off_screen["x"] = 234;
off_screen["y"] = 192;
off_screen["touch"] = true ;

local touch_data = { };
touch_data["touch"] = true ;

touch_data["x"] = 101;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 104;
touch_data["y"] = 88;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 110;
touch_data["y"] = 83;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 77;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 75;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 144;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 148;
touch_data["y"] = 68;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 156;
touch_data["y"] = 60;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 162;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 56;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 55;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 192;
touch_data["y"] = 55;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 195;
touch_data["y"] = 56;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 216;
touch_data["y"] = 62;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 224;
touch_data["y"] = 66;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 239;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 240;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 239;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 238;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 237;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 232;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 230;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 223;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 222;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 220;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 193;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 147;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 171;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 144;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 143;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 156;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 148;
touch_data["y"] = 136;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 131;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 128;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 110;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 127;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 122;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 115;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 194;
touch_data["y"] = 75;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 192;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 69;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 67;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 182;
touch_data["y"] = 68;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 69;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 176;
touch_data["y"] = 75;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 83;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 182;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 191;
touch_data["y"] = 82;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 194;
touch_data["y"] = 76;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 194;
touch_data["y"] = 118;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 192;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 112;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 110;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 112;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 176;
touch_data["y"] = 118;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 123;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 126;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 128;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 127;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 191;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 194;
touch_data["y"] = 119;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 166;
touch_data["y"] = 92;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 168;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 105;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 148;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 140;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 96;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 130;
touch_data["y"] = 97;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 127;
touch_data["y"] = 99;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 126;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 126;
touch_data["y"] = 104;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 127;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 130;
touch_data["y"] = 108;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 108;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 144;
touch_data["y"] = 107;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 105;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 152;
touch_data["y"] = 104;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 154;
touch_data["y"] = 103;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 154;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 45;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 202;
touch_data["y"] = 43;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 200;
touch_data["y"] = 43;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 186;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 44;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 144;
touch_data["y"] = 48;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 140;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 136;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 120;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 116;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 56;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 98;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 56;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 86;
touch_data["y"] = 55;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 82;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 70;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 64;
touch_data["y"] = 60;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 68;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 72;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 70;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 72;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 75;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 76;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 77;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 110;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 77;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 142;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 144;
touch_data["y"] = 72;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 148;
touch_data["y"] = 67;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 155;
touch_data["y"] = 59;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 55;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 166;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 186;
touch_data["y"] = 52;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 192;
touch_data["y"] = 51;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 195;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 204;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 48;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 203;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 206;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 205;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 204;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 201;
touch_data["y"] = 157;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 170;
touch_data["y"] = 160;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 159;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 150;
touch_data["y"] = 156;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 152;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 136;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 147;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 144;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 116;
touch_data["y"] = 143;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 144;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 95;
touch_data["y"] = 151;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 82;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 78;
touch_data["y"] = 151;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 76;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 76;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 78;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 82;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 136;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 86;
touch_data["y"] = 135;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 90;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 95;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 98;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 102;
touch_data["y"] = 131;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 104;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 108;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 52;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 124;
touch_data["y"] = 52;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 120;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 120;
touch_data["y"] = 39;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 32;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 112;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 97;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 93;
touch_data["y"] = 21;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 69;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 44;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 74;
touch_data["y"] = 52;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 72;
touch_data["y"] = 52;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 63;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 54;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 72;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 79;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 79;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 62;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 54;
touch_data["y"] = 76;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 75;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 143;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 54;
touch_data["y"] = 142;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 70;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 78;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 73;
touch_data["y"] = 143;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 54;
touch_data["y"] = 169;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 167;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 166;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 165;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 74;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 80;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 83;
touch_data["y"] = 156;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 88;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 105;
touch_data["y"] = 83;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 100;
touch_data["y"] = 83;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 87;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 88;
touch_data["y"] = 88;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 86;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 82;
touch_data["y"] = 90;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 91;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 72;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 69;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 70;
touch_data["y"] = 104;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 111;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 119;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 97;
touch_data["y"] = 123;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 123;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 81;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 44;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 120;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 36;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 36;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 114;
touch_data["y"] = 32;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 32;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 101;
touch_data["y"] = 24;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 24;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 90;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 56;
touch_data["y"] = 20;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 59;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 51;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 69;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 79;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 97;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 87;
touch_data["y"] = 88;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 88;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 76;
touch_data["y"] = 92;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 92;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 61;
touch_data["y"] = 96;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 62;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 96;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 135;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 69;
touch_data["y"] = 96;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 72;
touch_data["y"] = 135;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 74;
touch_data["y"] = 112;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 102;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 78;
touch_data["y"] = 118;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 97;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 78;
touch_data["y"] = 122;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 90;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 126;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 85;
touch_data["y"] = 136;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 77;
touch_data["y"] = 131;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 78;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 152;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 151;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 156;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 79;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 57;
touch_data["y"] = 160;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 73;
touch_data["y"] = 160;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 53;
touch_data["y"] = 165;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
emu.pause();
