local off_screen = { };
off_screen["x"] = 234;
off_screen["y"] = 192;
off_screen["touch"] = true ;

local touch_data = { };
touch_data["touch"] = true ;

touch_data["x"] = 194;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 194;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 188;
touch_data["y"] = 87;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 188;
touch_data["y"] = 83;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 194;
touch_data["y"] = 83;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 194;
touch_data["y"] = 70;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 228;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 234;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 236;
touch_data["y"] = 116;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 208;
touch_data["y"] = 116;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 192;
touch_data["y"] = 88;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 192;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 198;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 235;
touch_data["y"] = 115;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 207;
touch_data["y"] = 115;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 194;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 212;
touch_data["y"] = 91;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 221;
touch_data["y"] = 91;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 221;
touch_data["y"] = 103;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 212;
touch_data["y"] = 103;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 27;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 32;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 32;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 170;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 171;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 37;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 168;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 51;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 51;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 59;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 69;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 64;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 64;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 76;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 74;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 76;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 170;
touch_data["y"] = 89;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 170;
touch_data["y"] = 99;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 99;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 99;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 116;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 116;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 170;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 170;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 144;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 171;
touch_data["y"] = 144;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 171;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 154;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 144;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 159;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 169;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 164;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 164;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 57;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 72;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 62;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 62;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 67;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 62;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 62;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 72;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 77;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 77;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 87;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 92;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 92;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 122;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 119;
touch_data["y"] = 102;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 92;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 116;
touch_data["y"] = 114;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 114;
touch_data["y"] = 115;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 114;
touch_data["y"] = 122;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 115;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 131;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 120;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 131;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 115;
touch_data["y"] = 139;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 7;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 7;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 8;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 93;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 12;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 95;
touch_data["y"] = 12;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 93;
touch_data["y"] = 12;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 92;
touch_data["y"] = 15;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 15;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 16;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 91;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 44;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 39;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 39;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 59;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 59;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 59;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 81;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 76;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 76;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 96;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 96;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 96;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 111;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 101;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 111;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 123;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 123;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 143;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 94;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 163;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 163;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 168;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 178;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 99;
touch_data["y"] = 173;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 89;
touch_data["y"] = 173;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 68;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 68;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 73;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 73;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 42;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 43;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 48;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 68;
touch_data["y"] = 48;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 49;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 51;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 56;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 58;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 58;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 63;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 70;
touch_data["y"] = 63;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 70;
touch_data["y"] = 68;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 70;
touch_data["y"] = 63;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 63;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 88;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 72;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 70;
touch_data["y"] = 80;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 69;
touch_data["y"] = 87;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 88;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 86;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 78;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 103;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 98;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 108;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 115;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 112;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 112;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 108;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 115;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 122;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 74;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 122;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 72;
touch_data["y"] = 120;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 67;
touch_data["y"] = 120;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 66;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 135;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 135;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 65;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 71;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 75;
touch_data["y"] = 153;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
emu.pause();
