local off_screen = { };
off_screen["x"] = 234;
off_screen["y"] = 192;
off_screen["touch"] = true ;

local touch_data = { };
touch_data["touch"] = true ;

touch_data["x"] = 181;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 15;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 11;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 171;
touch_data["y"] = 10;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 11;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 164;
touch_data["y"] = 12;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 160;
touch_data["y"] = 14;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 16;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 154;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 148;
touch_data["y"] = 23;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 23;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 131;
touch_data["y"] = 23;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 128;
touch_data["y"] = 24;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 124;
touch_data["y"] = 26;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 120;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 31;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 114;
touch_data["y"] = 36;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 110;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 108;
touch_data["y"] = 44;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 105;
touch_data["y"] = 54;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 104;
touch_data["y"] = 58;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 64;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 102;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 103;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 104;
touch_data["y"] = 94;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 107;
touch_data["y"] = 108;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 108;
touch_data["y"] = 111;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 118;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 120;
touch_data["y"] = 127;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 126;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 124;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 128;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 128;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 148;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 152;
touch_data["y"] = 131;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 156;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 158;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 128;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 172;
touch_data["y"] = 123;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 121;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 119;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 176;
touch_data["y"] = 112;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 106;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 174;
touch_data["y"] = 95;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 64;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 174;
touch_data["y"] = 53;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 175;
touch_data["y"] = 47;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 176;
touch_data["y"] = 43;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 40;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 35;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 27;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 18;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 17;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 19;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 22;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 158;
touch_data["y"] = 27;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 159;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 162;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 164;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 32;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 177;
touch_data["y"] = 29;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 14;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 168;
touch_data["y"] = 14;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 151;
touch_data["y"] = 25;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 27;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 111;
touch_data["y"] = 45;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 105;
touch_data["y"] = 76;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 112;
touch_data["y"] = 112;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 108;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 116;
touch_data["y"] = 119;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 113;
touch_data["y"] = 44;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 118;
touch_data["y"] = 123;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 117;
touch_data["y"] = 43;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 125;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 121;
touch_data["y"] = 36;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 125;
touch_data["y"] = 33;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 123;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 129;
touch_data["y"] = 31;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 123;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 31;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 137;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 142;
touch_data["y"] = 126;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 141;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 145;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 149;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 131;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 28;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 157;
touch_data["y"] = 30;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 127;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 161;
touch_data["y"] = 32;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 126;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 34;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 124;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 36;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 174;
touch_data["y"] = 122;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 173;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 174;
touch_data["y"] = 38;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 131;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 127;
touch_data["y"] = 130;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 124;
touch_data["y"] = 131;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 122;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 123;
touch_data["y"] = 134;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 126;
touch_data["y"] = 140;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 127;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 130;
touch_data["y"] = 145;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 134;
touch_data["y"] = 148;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 138;
touch_data["y"] = 150;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 152;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 159;
touch_data["y"] = 158;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 164;
touch_data["y"] = 163;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 166;
touch_data["y"] = 167;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 170;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 175;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 172;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 168;
touch_data["y"] = 168;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 161;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 168;
touch_data["y"] = 157;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 167;
touch_data["y"] = 155;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 165;
touch_data["y"] = 152;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 163;
touch_data["y"] = 151;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 160;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 153;
touch_data["y"] = 146;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 147;
touch_data["y"] = 143;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 138;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 143;
touch_data["y"] = 136;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 138;
touch_data["y"] = 132;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 132;
touch_data["y"] = 129;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 127;
touch_data["y"] = 133;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 142;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 128;
touch_data["y"] = 137;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 140;
touch_data["y"] = 149;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 136;
touch_data["y"] = 136;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 169;
touch_data["y"] = 162;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 133;
touch_data["y"] = 141;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 41;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 182;
touch_data["y"] = 43;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 56;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 178;
touch_data["y"] = 67;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 92;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 180;
touch_data["y"] = 103;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 181;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 182;
touch_data["y"] = 113;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 116;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 117;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 183;
touch_data["y"] = 116;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 186;
touch_data["y"] = 103;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 93;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 188;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 195;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 88;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 199;
touch_data["y"] = 85;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 200;
touch_data["y"] = 83;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 200;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 199;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 197;
touch_data["y"] = 69;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 195;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 194;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 73;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 188;
touch_data["y"] = 65;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 187;
touch_data["y"] = 56;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 186;
touch_data["y"] = 50;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 185;
touch_data["y"] = 46;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 43;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 179;
touch_data["y"] = 100;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 109;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 184;
touch_data["y"] = 58;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 189;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 191;
touch_data["y"] = 75;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 84;
stylus.set(touch_data);
emu.frameadvance();
touch_data["x"] = 196;
touch_data["y"] = 71;
stylus.set(touch_data);
emu.frameadvance();
stylus.set(off_screen);
emu.frameadvance();
emu.pause();
